name: CI build-test-pack
on: [push]
jobs:
  build:
    name: Build and test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release --logger trx --results-directory "TestResults"
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
          name: TestResults
          path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Pack
      run: dotnet pack --no-restore --no-build --configuration Release --version-suffix CI-${{ github.run_id }} --output pkg
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
          name: LibDeflate-${{ matrix.os }}
          path: pkg/*
